apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbvol-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: "{{ .Values.postgres.storage.storageClassName }}"
  {{- end }}
